spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookingSystem?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Taipei&characterEncoding=utf8
    username: web
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  # HikariCP ???????????????
  datasource.hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 600000
    max-lifetime: 1800000
    connection-timeout: 30000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bookingsystem.bookingboot.entity
  configuration:
    map-underscore-to-camel-case: true   # ??? user_name -> Java userName

server:
  port: 8080
